apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJzb3VtZW5iaXN3YXMyMTIiLCJwYXNzd29yZCI6IkMwbGxlY3RpMG4iLCJlbWFpbCI6InNvdW1lbi5iaXN3YXMyMTJAZ21haWwuY29tIiwiYXV0aCI6ImMyOTFiV1Z1WW1semQyRnpNakV5T2tNd2JHeGxZM1JwTUc0PSJ9fX0=
kind: Secret
metadata:
  name: my-docker-account-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: maven-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maven-app
  template:
    metadata:
      labels:
        app: maven-app
    spec:
      imagePullSecrets:
        - name: my-docker-account-secret    
      containers:
      - name: maven-app-container
        image: clickoncloudkubernets/maven-app:${DOCKER_TAG}
        resources:
          limits:
            memory: "512Mi"
            cpu: "1000m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: maven-app-service
  namespace: default
  labels:
    app: maven-app
spec:
  type: ClusterIP
  selector:
    app: maven-app
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP      
